# Generated by Django 6.0.6 on 2026-06-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='分类名')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('keywords', models.TextField(blank=True, default='', help_text='匹配关键词，逗号分隔')),
                ('print_prompt', models.TextField(blank=True, default='', help_text='核心印花提示词')),
                ('extra_prompt', models.TextField(blank=True, default='', help_text='额外提示词')),
                ('negative_prompt', models.TextField(blank=True, default='', help_text='负面提示词')),
                ('prompt_file', models.CharField(blank=True, default='', help_text='.md文件路径', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '印花分类',
                'verbose_name_plural': '印花分类',
                'ordering': ['name'],
            },
        ),
    ]
