# Generated by Django 6.0.6 on 2026-06-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '执行中'), ('done', '已完成'), ('error', '失败')], default='pending', max_length=20)),
                ('progress', models.TextField(blank=True, default='', help_text='当前步骤描述')),
                ('result', models.JSONField(blank=True, default=dict, help_text='导入结果')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '导入任务',
                'verbose_name_plural': '导入任务',
            },
        ),
    ]
