# Generated by Django 6.0.6 on 2026-06-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_importtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='printcategory',
            name='style_context',
            field=models.TextField(blank=True, default='', help_text='场景/灯光/摄影风格（不含服装）'),
        ),
        migrations.AlterField(
            model_name='printcategory',
            name='print_prompt',
            field=models.TextField(blank=True, default='', help_text='印花设计描述（纯印花，不含服装）'),
        ),
    ]
