# Generated by Django 6.0.6 on 2026-06-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_printcategory_style_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='预设名')),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('content', models.TextField(help_text='完整正向 prompt 内容')),
                ('negative_prompt', models.TextField(blank=True, default='', help_text='负面提示词')),
                ('md_file', models.FileField(blank=True, help_text='原始 .md 文件', upload_to='prompts/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '提示词预设',
                'verbose_name_plural': '提示词预设',
                'ordering': ['-created_at'],
            },
        ),
    ]
