# Generated by Django 6.0.6 on 2026-06-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_promptpreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptpreset',
            name='shirt_color',
            field=models.CharField(choices=[('white', '白色 T 恤'), ('black', '黑色 T 恤'), ('other', '其他')], default='white', help_text='T 恤颜色分类', max_length=16),
        ),
    ]
