# Generated by Django 6.0.6 on 2026-06-06 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_promptpreset_shirt_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintDesignPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='预设名')),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('shirt_color', models.CharField(choices=[('white', '白色 T 恤'), ('black', '黑色 T 恤'), ('other', '其他')], default='white', help_text='T 恤颜色分类', max_length=16)),
                ('content', models.TextField(help_text='只描述平面印花图案，不描述T恤/衣架/场景')),
                ('negative_prompt', models.TextField(blank=True, default='', help_text='负面提示词')),
                ('variation_pool', models.JSONField(blank=True, default=dict, help_text='配色/构图/元素/质感随机池')),
                ('md_file', models.FileField(blank=True, help_text='原始 .md 文件', upload_to='print_prompts/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '印花提示词预设',
                'verbose_name_plural': '印花提示词预设',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_color', models.CharField(choices=[('white', '白色 T 恤'), ('black', '黑色 T 恤'), ('other', '其他')], default='white', max_length=16)),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True, default='')),
                ('variation_metadata', models.JSONField(blank=True, default=dict)),
                ('seed', models.IntegerField(default=0)),
                ('raw_image', models.ImageField(blank=True, null=True, upload_to='prints/raw/%Y/%m/')),
                ('transparent_image', models.ImageField(blank=True, null=True, upload_to='prints/transparent/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='categories.printdesignpreset')),
            ],
            options={
                'verbose_name': '印花设计',
                'verbose_name_plural': '印花设计',
                'ordering': ['-created_at'],
            },
        ),
    ]
