# Generated by Django 6.0.6 on 2026-06-04 09:04

import apps.templates_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TShirtTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='模板名称，如"白色基础款圆领"', max_length=128)),
                ('image', models.ImageField(blank=True, help_text='T恤底图（建议1024x1024以上PNG）', storage=apps.templates_app.storage.TemplateImageStorage(), upload_to='tshirt_templates/%Y/%m/')),
                ('color', models.CharField(choices=[('white', '白色'), ('black', '黑色'), ('gray', '灰色'), ('navy', '深蓝'), ('red', '红色'), ('other', '其他颜色')], default='white', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'T恤模板',
                'verbose_name_plural': 'T恤模板',
                'ordering': ['-created_at'],
            },
        ),
    ]
