# Generated by Django 6.0.6 on 2026-06-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TShirtTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, upload_to='templates/%Y/%m/')),
                ('color', models.CharField(choices=[('white', '白色'), ('black', '黑色'), ('gray', '灰色'), ('navy', '深蓝'), ('red', '红色'), ('other', '其他颜色')], default='white', max_length=16)),
                ('prompt_body', models.TextField(blank=True, default='', help_text='豆包生成的版型提示词（含版型/颜色/领型/袖长）')),
                ('fabric', models.CharField(blank=True, default='', help_text='面料描述，如 premium cotton, 230gsm', max_length=256)),
                ('sizes', models.CharField(blank=True, default='XS,S,M,L,XL,XXL,3XL,4XL', help_text='可选尺码，逗号分隔', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'T恤模板',
                'verbose_name_plural': 'T恤模板',
                'ordering': ['-created_at'],
            },
        ),
    ]
