# Generated by Django 6.0.6 on 2026-06-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirttemplate',
            name='is_pod_template',
            field=models.BooleanField(default=False, help_text='可用于 POD 贴图模式'),
        ),
        migrations.AddField(
            model_name='tshirttemplate',
            name='print_area_height',
            field=models.IntegerField(blank=True, help_text='印花区域高度 (px)', null=True),
        ),
        migrations.AddField(
            model_name='tshirttemplate',
            name='print_area_width',
            field=models.IntegerField(blank=True, help_text='印花区域宽度 (px)', null=True),
        ),
        migrations.AddField(
            model_name='tshirttemplate',
            name='print_area_x',
            field=models.IntegerField(blank=True, help_text='印花区域 X 坐标 (px)', null=True),
        ),
        migrations.AddField(
            model_name='tshirttemplate',
            name='print_area_y',
            field=models.IntegerField(blank=True, help_text='印花区域 Y 坐标 (px)', null=True),
        ),
        migrations.AddField(
            model_name='tshirttemplate',
            name='template_view',
            field=models.CharField(default='front', help_text='模板视图 (front only in v1)', max_length=16),
        ),
    ]
