# Generated by Django 6.0.6 on 2026-06-04 09:06

import apps.patterns.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='原始印花图片', storage=apps.patterns.storage.PatternImageStorage(), upload_to='patterns/%Y/%m/')),
                ('source_type', models.CharField(choices=[('clean_print', '干净印花（透明底）'), ('model_photo', '模特上身图'), ('product_photo', '产品平铺图')], default='clean_print', help_text='图片来源类型（决定是否需要抠图预处理）', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '原始印花',
                'verbose_name_plural': '原始印花',
                'ordering': ['-created_at'],
            },
        ),
    ]
