# Generated by Django 4.2.30 on 2026-06-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='图片 SHA256 哈希，用于查重', max_length=64),
        ),
    ]
