# Generated by Django 6.0.6 on 2026-06-05 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('core', '0001_initial'),
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('size_info', models.CharField(blank=True, default='', max_length=256)),
                ('status', models.CharField(choices=[('pending', '等待生成'), ('processing', '生成中'), ('completed', '已完成'), ('failed', '生成失败'), ('text_pending', '待补全文本')], db_index=True, default='pending', max_length=20)),
                ('seed', models.IntegerField(default=0)),
                ('background', models.CharField(blank=True, default='', max_length=256)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.printcategory')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.country')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='templates_app.tshirttemplate')),
            ],
            options={
                'verbose_name': '生成产品',
                'verbose_name_plural': '生成产品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mockup_image', models.ImageField(blank=True, null=True, upload_to='products/skus/%Y/%m/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.product')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='templates_app.tshirttemplate')),
            ],
            options={
                'verbose_name': '产品SKU',
                'verbose_name_plural': '产品SKU',
            },
        ),
    ]
