# Generated by Django 6.0.6 on 2026-06-04 09:07

import apps.products.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('patterns', '0001_initial'),
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_image', models.ImageField(blank=True, help_text='生成的印花图', null=True, storage=apps.products.storage.ProductImageStorage(), upload_to='products/prints/%Y/%m/')),
                ('mockup_image', models.ImageField(blank=True, help_text='印花+T恤效果图', null=True, storage=apps.products.storage.ProductImageStorage(), upload_to='products/mockups/%Y/%m/')),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('size_info', models.CharField(blank=True, default='', help_text='尺码信息', max_length=256)),
                ('status', models.CharField(choices=[('pending', '等待生成'), ('processing', '生成中'), ('completed', '已完成'), ('failed', '生成失败'), ('text_pending', '待补全文本')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.country')),
                ('pattern', models.ForeignKey(help_text='参考的原始印花', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='patterns.pattern')),
                ('template', models.ForeignKey(help_text='使用的T恤模板', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='templates_app.tshirttemplate')),
            ],
            options={
                'verbose_name': '生成产品',
                'verbose_name_plural': '生成产品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('preprocess', '预处理（抠图）'), ('image_gen', '印花生成'), ('text_gen', '文本生成'), ('write_storage', '存储写入')], max_length=20)),
                ('model_used', models.CharField(blank=True, default='', max_length=128)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='耗时（毫秒）')),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to='products.product')),
            ],
            options={
                'verbose_name': '生成记录',
                'verbose_name_plural': '生成记录',
                'ordering': ['product', 'created_at'],
            },
        ),
    ]
