# Generated by Django 6.0.6 on 2026-06-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_promptpreset'),
        ('products', '0001_initial'),
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prompt_preset',
            field=models.ForeignKey(blank=True, help_text='直接使用 .md 提示词预设', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.promptpreset'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.printcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='templates_app.tshirttemplate'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='templates_app.tshirttemplate'),
        ),
    ]
