# Generated by Django 6.0.6 on 2026-06-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_prompt_preset_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='template_key',
            field=models.CharField(blank=True, default='', help_text='V6 产品模板 key，如 tshirt_white', max_length=64),
        ),
    ]
