# Generated by Django 6.0.6 on 2026-06-06 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_printdesignpreset_printdesign'),
        ('products', '0003_product_template_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='generation_mode',
            field=models.CharField(choices=[('direct', 'AI 直出'), ('pod', 'POD 贴图')], default='direct', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='print_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.printdesign'),
        ),
    ]
