# Generated by Django 6.0.6 on 2026-06-07 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_generation_mode_product_print_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='sku_name',
            field=models.CharField(blank=True, default='', help_text='SKU 显示名称（如 Black/White）', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='generation_mode',
            field=models.CharField(choices=[('direct', 'AI 直出'), ('pod', 'POD 贴图'), ('source_image', '图片素材')], default='direct', max_length=16),
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assets/source/%Y/%m/')),
                ('color', models.CharField(choices=[('black', '黑色'), ('white', '白色')], max_length=16)),
                ('original_filename', models.CharField(blank=True, default='', max_length=512)),
                ('source_folder', models.CharField(blank=True, default='', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_assets', to='products.product')),
            ],
            options={
                'verbose_name': '图片素材',
                'verbose_name_plural': '图片素材',
                'ordering': ['-created_at'],
            },
        ),
    ]
