# Generated by Django 6.0.6 on 2026-06-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productsku_sku_name_alter_product_generation_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageasset',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
